compcrdwebhook:
  displayName: Component-CRD-Webhook
  fileName: compcrdwebhook
  
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .oda-webhook.image
  valuesPathVersion: .oda-webhook.version
  valuesPathPrereleaseSuffix: .oda-webhook.prereleaseSuffix
  
  paths:
    - source/webhooks/webhook-dockerfile
    - source/webhooks/implementation/**/*
  buildContext: source/webhooks
  # default is "Dockerfile" in buildContext
  buildDockerfile: source/webhooks/webhook-dockerfile  
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

  
component-operator:
  displayName: Component-operator
  fileName: component-operator
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .component-operator.deployment.compopImage
  valuesPathVersion: .component-operator.deployment.compopVersion
  valuesPathPrereleaseSuffix: .component-operator.deployment.compopPrereleaseSuffix
  paths:
    - source/operators/component-management/*
  buildContext: source/operators/component-management
  # default is "Dockerfile" in buildContext
  buildDockerfile: source/operators/component-management/component-operator-dockerfile
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

identityconfig-operator-keycloak:
  displayName: Identityconfig-operator-keycloak
  fileName: identityconfig-operator-keycloak
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .identityconfig-operator-keycloak.deployment.idkopImage
  valuesPathVersion: .identityconfig-operator.deployment.idkopVersion
  valuesPathPrereleaseSuffix: .identityconfig-operator.deployment.idkopPrereleaseSuffix
  paths:
    - source/operators/identity-config/keycloak/*
  buildContext: source/operators/identity-config/keycloak
  # default is "Dockerfile" in buildContext
  buildDockerfile: source/operators/identity-config/keycloak/identityconfig-operator-dockerfile
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

identity-listener-keycloak:
  displayName: identity-Listener-keycloak
  fileName: identity-listener-keycloak

  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .identityconfig-operator-keycloak.deployment.idlistkeyImage
  valuesPathVersion: .identityconfig-operator-keycloak.deployment.idlistkeyVersion
  valuesPathPrereleaseSuffix: .identityconfig-operator-keycloak.deployment.idlistkeyPrereleaseSuffix

  paths:
    - source/operators/identity-config/keycloak/identity-listener-keycloak/*
  buildContext: source/operators/identity-config/keycloak/identity-listener-keycloak
  # default is "Dockerfile" in buildContext
  buildDockerfile: source/operators/identity-config/keycloak/identity-listener-keycloak/identity-listenet-keycloak-dockerfile
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

api-operator-istio:
  displayName: API-operator-istio
  fileName: api-operator-istio
  
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .api-operator-istio.deployment.apiopImage
  valuesPathVersion: .api-operator-istio.deployment.apiopVersion
  valuesPathPrereleaseSuffix: .api-operator-istio.deployment.apiopPrereleaseSuffix
  
  paths:
    - source/operators/api-management/istio/*
  buildContext: source/operators/api-management/istio
  # default is "Dockerfile" in buildContext
  buildDockerfile: source/operators/api-management/istio/api-operator-istio-dockerfile
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64


dependentapi-simple-operator:
  displayName: DependentAPI-Simple-Operator
  fileName: dependentapi-simple-operator
  
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .dependentapi-simple-operator.image
  valuesPathVersion: .dependentapi-simple-operator.version
  valuesPathPrereleaseSuffix: .dependentapi-simple-operator.prereleaseSuffix
  
  paths:
    - source/operators/dependentApiSimpleOperator/docker/**/*
  buildContext: source/operators/dependentApiSimpleOperator/docker
  # default is "Dockerfile" in buildContext
  #buildDockerfile: 
  testDockerfile: source/operators/dependentApiSimpleOperator/docker/DockerfileTest
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

tmf638-service-inventory-api:
  displayName: TMF-638 Service Inventory API
  fileName: tmf638-service-inventory-api
  
  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .dependentapi-simple-operator.serviceInventoryAPI.image
  valuesPathVersion: .dependentapi-simple-operator.serviceInventoryAPI.version
  valuesPathPrereleaseSuffix: .dependentapi-simple-operator.serviceInventoryAPI.prereleaseSuffix
  
  paths:
    - source/tmf-services/TMF638_Service_Inventory/**/*
  buildContext: source/tmf-services/TMF638_Service_Inventory
  # default is "Dockerfile" in buildContext
  #buildDockerfile: 
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

  
secretsmanagement-operator:  
  displayName: SecretsManagement-Operator
  fileName: secretsmanagement-operator

  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .secretsmanagement-operator.image
  valuesPathVersion: .secretsmanagement-operator.version
  valuesPathPrereleaseSuffix: .secretsmanagement-operator.prereleaseSuffix

  paths:
  - source/operators/secretsmanagementOperator-hc/docker/**/*
  buildContext: source/operators/secretsmanagementOperator-hc/docker
  # default is "Dockerfile" in buildContext
  #buildDockerfile:
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64

  
secretsmanagement-sidecar:
  displayName: SecretsManagement-Sidecar
  fileName: secretsmanagement-sidecar

  valuesYamlFile: charts/canvas-oda/values.yaml
  valuesPathImage: .secretsmanagement-operator.sidecarImage
  valuesPathVersion: .secretsmanagement-operator.sidecarVersion
  valuesPathPrereleaseSuffix: .secretsmanagement-operator.sidecarPrereleaseSuffix

  paths:
  - source/operators/secretsmanagementOperator-hc/sidecar/docker/**/*
  buildContext: source/operators/secretsmanagementOperator-hc/sidecar/docker
  # default is "Dockerfile" in buildContext
  #buildDockerfile:
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64
  

baseimage-kubectl-curl:
  displayName: Baseimage-Kubectl-cURL
  fileName: baseimage-kubectl-curl
  
  valuesYamlFile: baseimages/kubectl-curl/version.yaml
  valuesPathImage: .image
  valuesPathVersion: .version
  valuesPathPrereleaseSuffix: .prereleaseSuffix
  
  paths:
    - baseimages/kubectl-curl/**/*
  buildContext: baseimages/kubectl-curl
  # default is "Dockerfile" in buildContext
  #buildDockerfile:   
  # default is "linux/amd64,linux/arm64"
  #platforms: linux/amd64,linux/arm64
