apiVersion: v1
kind: Secret
metadata:
  name: component-operator-secret
  labels:
    {{- include "component-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_USER: {{ .Values.credentials.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.credentials.pass | b64enc | quote }}
