apiVersion: v1
kind: Service
metadata:
  name: idconfop
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{.Values.deployment.operatorName}} #link service to Pod and not individual container
    {{- include "component-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5000
    targetPort: idconfop
    name: idconfop
  type: NodePort
  selector:
    app: {{.Values.deployment.operatorName}}
