apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "identityconfig.oda.tmforum.org"
  annotations:
    cert-manager.io/inject-ca-from:  {{ printf "%s/%s" .Release.Namespace .Values.global.certificate.appName  }}
spec:
  scope: "Namespaced"
  group: "oda.tmforum.org"
  names:
    plural: "identityconfigs"
    singular: "identityconfig"
    kind: "Identityconfig"
  conversion:
    strategy: Webhook
    # webhookClientConfig is required when strategy is `Webhook` and it configures the webhook endpoint to be called by API server.
    webhook:
      conversionReviewVersions: ["v1beta4"]
      clientConfig:
        service:
          namespace: {{ .Release.Namespace}}
          name: {{ .Values.global.certificate.appName}}
          path: /
          port: 443
  versions:
  - name: "v1beta4"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              controllerRole:
                description: This is the name of the role that the Canvas controllers will use to interact with the component's APIs.
                  It must exist in the roles exposed by the partyRole API.
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.summary/status.deployment_status





