apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "identityconfigs.oda.tmforum.org"
  annotations:
    cert-manager.io/inject-ca-from:  {{ printf "%s/%s" .Release.Namespace .Values.global.certificate.appName  }}
spec:
  scope: "Namespaced"
  group: "oda.tmforum.org"
  names:
    plural: "identityconfigs"
    singular: "identityconfig"
    kind: "IdentityConfig"
  versions:
  - name: "v1beta4"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              controllerRole:
                description: This is the name of the role that the Canvas controllers will use to interact with the component's APIs.
                type: string
              controllerRole:
                description: This is the name of the role that the Canvas controllers will use to interact with the component's APIs.
                type: string 
              componentRole:
                description: This allows components to declare statically defined roles that should be configured in Identity Management solution. 
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string   
              partyRoleAPI:
                description: This is the name of the API that the component will expose to allow Canvas to manage party roles.
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the API
                  specification:
                    type: array
                    items:
                      type: string
                      format: url
                    description: >
                      url to the specification of the API, if required. e.g. url to the swagger file for Open API.
                      This is an array of strings to allow for multiple specifications (e.g. to support Gen-4 and Gen-5 Open-APIs)
                    minItems: 1
                  apiType:
                    type: string
                    enum:
                    - openapi
                    description: The type of API specification. Currently only OpenAPI (swagger) is supported.
                  apiSDO:
                    type: string
                    description: (optional) The name of the SDO (Standards Definition Organization) that defines the API standard                          
                  implementation:
                    type: string
                    description: The name of the service where the implementation of the API is found
                  path:
                    type: string
                    description: The path to the root of the API
                  developerUI:
                    type: string
                    description: (optional) The path to the developer User Interface for the API
                  port:
                    type: integer
                    description: The port where the API is exposed
                  resources:
                    type: array
                    items:
                      type: object
                    description: Resources is an optional list of resources that are exposed by the API.
                  required:
                    type: boolean
                    description: Required is a flag that indicates whether the API is required or not.
                required:
                - name
                - apiType
                - implementation
                - path
                - port                             
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: identity_provider
      type: string
      description: Identity provider
      jsonPath: .status.identityConfig.identityProvider   
    - name: listner-registered
      type: boolean
      description: If component uses dynamic roles via exposing API, canvas creates listner to listen for changes.
      jsonPath: .status.identityConfig.listenerRegistered   



