apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peerings.kopf.dev
spec:
  group: kopf.dev
  names:
    kind: Peering
    plural: peerings
    singular: peering
    shortNames:
      - pr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                id:
                  type: string
                election:
                  type: string
            status:
              type: object
              properties:
                leader:
                  type: string
                started:
                  type: string
                renews:
                  type: string
---
apiVersion: kopf.dev/v1
kind: Peering
metadata:
  name: default  # You can choose a name here; "default" is commonly used
  namespace: components # Replace with your operator's namespace
spec:
  id: default  # Peering ID used by all operators to coordinate
  election: leases
