apiVersion: v1
kind: Secret
metadata:
  name: identityconfig-operator-keycloak-secret
  labels:
    {{- include "identityconfig-operator-keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_USER: {{ .Values.credentials.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.credentials.pass | b64enc | quote }}
