apiVersion: v1
kind: Service
metadata:
  name: idlistkey
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{.Values.deployment.operatorName}} #link service to Pod and not individual container
    {{- include "identityconfig-operator-keycloak.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5000
    targetPort: idlistkey
    name: idlistkey
  type: NodePort
  selector:
    app: {{.Values.deployment.operatorName}}
