name: Lint Python code
on: 
  pull_request:
    branches:
      - main
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with: 
          src: |
            ./automation/generators/dockerbuild-workflow-generator
            ./source/operators/component-management
            ./source/operators/api-management/istio
            ./source/operators/dependentApiSimpleOperator
            ./source/operators/secretsmanagementOperator-hc
